flux-framework/flux-operator

README.md
TODO.md
api/v1alpha1/flux_types.go
api/v1alpha1/fluxsetup_types.go
controllers/flux/flux_controller.go
controllers/flux/fluxsetup_controller.go
controllers/flux/labels.go
controllers/flux/statefulset.go

This will add the creation of the stateful set! I'm going to be making small PRs, in increments where even a small piece of something is working. In this case I have the stateful set created! I've never used one of these before so for next steps I'm going to see what the heck it is :)
For the peanut gallery, the TIL is that if you don't apply this:
```
Status: appsv1.StatefulSetStatus{},
```
Your stateful set will report it has incorrect labels (an empty map) and I tried a lot of things until realizing we needed that.
Programming in Go is pure joy.

Adding skeleton for statefulset

---

AUTHORS
COPYING
LICENSE
NOTICE.LLNS
README.md
api/v1alpha1/flux_types.go
api/v1alpha1/fluxsetup_types.go
api/v1alpha1/groupversion_info.go
controllers/core/core.go
controllers/flux/configmap.go
controllers/flux/flux_controller.go
controllers/flux/fluxsetup_controller.go
controllers/flux/job.go
controllers/flux/labels.go
controllers/flux/logging.go
controllers/flux/secret.go
controllers/flux/service.go
controllers/flux/statefulset.go
controllers/flux/volumes.go
main.go

adding missing LICENSE information to match spack/flux projects

---

docker/README.md
docker/demo-lammps-mpi/Dockerfile

install extra dependency pdsh for starting flux

---

.github/workflows/build-deploy.yaml
.gitignore
Dockerfile
Makefile
README.md
bundle.Dockerfile
bundle/manifests/flux-framework.org_miniclusters.yaml
bundle/manifests/operator-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/operator-manager-config_v1_configmap.yaml
bundle/manifests/operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml
config/manager/controller_manager_config.yaml
config/manager/kustomization.yaml
config/manifests/bases/operator.clusterserviceversion.yaml
controllers/flux/job.go
controllers/flux/suite_test.go

I am not sure what we will want for a more production deployment (and I need to read up on what a catalog is) but the base docker image and bundle to install directly seems like a good idea! This workflow willadd in those two things, and when we know how we want to deploy this we can tweak further. I also need to poke around and see what others are doing.

build: testing docker build and bundle

---

.github/workflows/build-deploy.yaml

add catalog build and push

---

README.md
api/v1alpha1/minicluster_types.go
config/crd/bases/flux-framework.org_miniclusters.yaml
config/manager/kustomization.yaml
config/rbac/role.yaml
config/samples/flux-framework.org_v1alpha1_minicluster.yaml
controllers/flux/minicluster.go
controllers/flux/minicluster_controller.go

It came down to RBACs... of course!!
The one gotcha was with respect to the ip addresses - for some reason it wasn't reconciling when the ips weren't available (and then they would show up, but :cricket: ! What I realized is that returning a result with Requeue: true and nil for the error was _not_ sufficient for the reconcile - I needed to return a `fmt.Errorf`  and then it magically worked.
@zekemorton as I was working on this I think we (if possible) want to not just check for a minimum size, but the size requested vs  a maximum number of pods that can be supported. I think when I was originally trying with a number too big for my cluster it was silently failing - creating the MiniCluster object but with absolutely no events.
I will want to run this once through in completion again …

production tested and working!

---

.github/workflows/docs.yml

debugging docs environment

---

docs/development/aws.md
docs/development/index.md

adding eks deploy example

---

controllers/flux/templates/wait.sh
examples/flux-restful/minicluster-lammps.yaml

inspect changes

---

docs/getting_started/user-guide.md

add link to validator

---

docs/tutorials/state.md
sdk/python/v1alpha1/examples/state-pending-jobs-minicluster.py

this example testing increasing and decreasing size, and adding notes to the state documentation.

add example to pause running queue

---

.github/workflows/main.yaml
controllers/flux/job.go
controllers/flux/minicluster.go
controllers/flux/service.go
controllers/flux/templates/wait.sh
docs/tutorials/index.md
docs/tutorials/services.md
examples/tests/nginx-service/minicluster.yaml
examples/tests/nginx-service/test.out.correct

- Adding an ability to define a second container with a port service, with an exposed k8s service
- Examples with ORAS and nginx
- Tutorial with nginx

first example with second container service

---

hack/python-sdk/template/setup.py
sdk/python/v1alpha1/CHANGELOG.md
sdk/python/v1alpha1/fluxoperator/client.py
sdk/python/v1alpha1/setup.py

we need the get pods function to be allowed to get a 404 response when we are waiting for termination

debug python sdk termination log

---

docs/tutorials/services.md
examples/launchers/merlin/minicluster.yaml
examples/launchers/merlin/services.yaml

This is not perfect - I think likely merlin itself needs some work/discussion for the details, but it is a good getting started tutorial

add start of merlin example

---

.github/workflows/helm.yaml
Makefile
chart/.helmignore
chart/Chart.yaml
chart/templates/_helpers.tpl
chart/templates/deployment.yaml
chart/templates/leader-election-rbac.yaml
chart/templates/manager-config.yaml
chart/templates/manager-rbac.yaml
chart/templates/metrics-reader-rbac.yaml
chart/templates/metrics-service.yaml
chart/templates/minicluster-crd.yaml
chart/templates/proxy-rbac.yaml
chart/values.yaml
docs/getting_started/user-guide.md

test adding helm chart

---

.github/workflows/main.yaml
api/v1alpha1/minicluster_types.go
api/v1alpha1/swagger.json
api/v1alpha1/zz_generated.openapi.go
chart/templates/minicluster-crd.yaml
config/crd/bases/flux-framework.org_miniclusters.yaml
controllers/flux/templates/wait.sh
docs/tutorials/index.md
docs/tutorials/singularity.md
docs/tutorials/volumes.md
examples/dist/flux-operator.yaml
examples/singularity/minicluster-hello-world.yaml
examples/singularity/minicluster-prepull.yaml
examples/tests/singularity/minicluster.yaml
sdk/python/v1alpha1/docs/Commands.md
sdk/python/v1alpha1/fluxoperator/models/commands.py

This might be a much better strategy than requiring the user to build a custom container that also has flux!

adding singularity examples

---

README.md
api/v1alpha1/minicluster_types.go
api/v1alpha1/swagger.json
api/v1alpha1/zz_generated.openapi.go
chart/templates/minicluster-crd.yaml
config/crd/bases/flux-framework.org_miniclusters.yaml
config/manager/kustomization.yaml
controllers/flux/minicluster.go
controllers/flux/templates/wait.sh
docs/deployment/google/includes/basic-setup.md
docs/getting_started/custom-resource-definition.md
examples/dist/flux-operator.yaml
examples/tests/lammps/minicluster.yaml
sdk/python/v1alpha1/docs/LoggingSpec.md
sdk/python/v1alpha1/examples/time-minicluster-lammps.py
sdk/python/v1alpha1/fluxoperator/client.py
sdk/python/v1alpha1/fluxoperator/models/logging_spec.py
sdk/python/v1alpha1/fluxoperator/resource/pods.py

I need to test this on a larger cluster before I am confident it is working as expected - I do not have enough cpus for our lab google account and need to use my personal account

wip to add pod completion

---

Makefile
api/v1alpha1/minicluster_types.go
api/v1alpha1/swagger.json
api/v1alpha1/zz_generated.openapi.go
chart/templates/minicluster-crd.yaml
config/crd/bases/flux-framework.org_miniclusters.yaml
controllers/flux/templates/wait.sh
docs/getting_started/custom-resource-definition.md
examples/dist/flux-operator.yaml
hack/python-sdk/template/setup.py
sdk/python/v1alpha1/CHANGELOG.md
sdk/python/v1alpha1/docs/FluxSpec.md
sdk/python/v1alpha1/examples/interactive-submit.py
sdk/python/v1alpha1/fluxoperator/client.py
sdk/python/v1alpha1/fluxoperator/models/flux_spec.py
sdk/python/v1alpha1/setup.py

I accidentally messed up the first branch - this should only have the addition of add/wrap.

add support for flux wrap around flux start

---

docs/tutorials/elasticity.md
docs/tutorials/index.md
docs/tutorials/scaling.md
examples/elasticity/basic/kind-config.yaml
examples/elasticity/basic/minicluster.yaml
examples/elasticity/basic/three_bears.py
examples/elasticity/rbac.yaml

This is the first prototype of true elasticity, controlled by an application. For fun we tell a story of Gopherlocks and the (not) three bears! Demo and more description here https://asciinema.org/a/585802.

Add first elasticity demo!

---

examples/elasticity/google/autoscale/README.md
examples/elasticity/google/autoscale/fluxcluster.py
examples/elasticity/google/autoscale/test-scale.py

we will do more work with this to integrate the flux operator in too.

add base scripts to test GKE elasticity

---

.github/workflows/docs.yaml
docs/requirements.txt

The issue is pydantic - we need to pin to 1.10.8 for it to work! I opened a bug: https://github.com/sphinx-doc/sphinx/issues/11479

test for doc bug fix

---

.github/workflows/release.yaml
Makefile
docs/conf.py
docs/deployment/ibm.md
docs/development/creation.md
docs/development/developer-guide.md
docs/getting_started/user-guide.md

A little bit of cleanup and better instruction for installing from a release!

updates to docs

---

api/v1alpha1/minicluster_types.go
api/v1alpha1/swagger.json
api/v1alpha1/zz_generated.openapi.go
chart/templates/minicluster-crd.yaml
config/crd/bases/flux-framework.org_miniclusters.yaml
controllers/flux/templates/wait.sh
docs/getting_started/custom-resource-definition.md
examples/dist/flux-operator-arm.yaml
examples/dist/flux-operator.yaml
sdk/python/v1alpha1/docs/FluxSpec.md
sdk/python/v1alpha1/fluxoperator/models/flux_spec.py

for older container that still require flux mini submit (or another derivative) this is needed.

add support to customize flux submit command

---

.github/workflows/main.yaml
controllers/flux/job.go
pkg/flux/view.go
script/check-output.sh

This seems to / maybe works? I don't know why my first test a few night ago didn't - I suppose we will find out more here!

test init container design instead of sidecar

---

.github/workflows/docs.yaml
docs/about/contributing.md
docs/conf.py
docs/requirements.txt

https://github.com/jbms/sphinx-immaterial/issues/412

pin sphinx immaterial to previously working version

---

api/v1alpha2/minicluster_types.go
api/v1alpha2/swagger.json
api/v1alpha2/zz_generated.openapi.go
chart/templates/minicluster-crd.yaml
config/crd/bases/flux-framework.org_miniclusters.yaml
controllers/flux/job.go
docs/getting_started/custom-resource-definition.md
examples/dist/flux-operator-arm.yaml
examples/dist/flux-operator.yaml
sdk/python/v1alpha2/docs/PodSpec.md
sdk/python/v1alpha2/fluxoperator/models/pod_spec.py

I am primarily testing what these features add (or do not add to a user space kubernetes environment. So far, I do not see any changes. It doesn't hurt to add for others to use/test.

feat: hostIPC and hostPID
