- README.md
- TODO.md
- controllers/flux/volumes.go
Before there was an error with the statefulset spec, and I have added a missing Name and fixed paths to be relative.
The thing to next debug is why the stateful set pods cannot see the config maps they need
> fixing statefulset creation

- .github/workflows/build-matrices.yaml
- docker/README.md
- docker/demo-lammps-mpi/Dockerfile
- docker/demo-lammps-mpi/uptodate.yaml
this set of automated builds will prepare several bases for an operator demo. The container builds are under docker, and designed so we can add any new set of subfolders and uptodate.yaml files that will result in matrix builds.
I tried the demo locally and think it worked? Haven't used laamps before!
> adding demo containers with flux laamps and mpi

- .github/workflows/build-matrices.yaml
- docker/README.md
- docker/demo-lammps-mpi/Dockerfile
we need to ensure that the lmp executable is available to the flux user, and not just root (it was by default installed to root home). We also should demonstrate creating the flux user and ensuring that permissions are set so he/she/it/they has access to the files we plan to exec. These small tweaks (per my local testing) should get the whole demo running as we expect.
> testing updated container build

- api/v1alpha1/minicluster_types.go
- config/samples/flux-framework.org_v1alpha1_minicluster.yaml
- controllers/flux/job.go
This PR adds in support for imagePullSecrets. 
To accomplish this goal, the PR adds in a new optional specification `imagePullSecrets` that accepts a list of strings. These strings represent secrets that already exist that contain the image registry credentials. This was implemented by adding the new parameter in the minicluster_types and then adding the pull secret to the podspec in the job.
One point of discussion is the list implementation. The idea here is that the podspec takes a list of imagePullSecrets because a pod can use multiple images and potentially need multiple pull secrets. In our current architecture, users can only specify a single image, so perhaps it would be simpler to reduce this parameter to just a string instead? I could go either way in this regard.
I tested the …
> added support for image pull secrets

- README.md
- config/samples/flux-framework.org_v1alpha1_minicluster.yaml
- controllers/flux/minicluster.go
- controllers/flux/templates/wait.sh
- controllers/flux/volumes.go
we need to be able to switch between a persistent volume claim (for production) and a local mount (for development). This example I tested and it works for local and eks. I'm going to try and PR to @milroy private repo with complete instructions for eks.
> final tweaks for production volumes

- README.md
- TODO.md
- api/v1alpha1/minicluster_types.go
- config/crd/bases/flux-framework.org_miniclusters.yaml
- config/samples/flux-framework.org_v1alpha1_minicluster.yaml
- controllers/flux/job.go
- controllers/flux/minicluster.go
- controllers/flux/minicluster_controller.go
- controllers/flux/service.go
- controllers/flux/templates/wait.sh
This isn't ready for review! I'm still figuring out how to expose the running service (inside the indexed job pod 0) to the external client. So far I've tried creating the service with an exposed port and ingress:
```console
$ kubectl get -n flux-operator svc
NAME                   TYPE       CLUSTER-IP       EXTERNAL-IP     PORT(S)          AGE
flux-restful-service   NodePort   10.110.131.130   192.168.0.194   5000:31766/TCP   7s
$ kubectl get -n flux-operator ingress
NAME                   CLASS    HOSTS   ADDRESS   PORTS   AGE
flux-restful-service   <none>   *                 80      13s
```
But no luck! If anyone has ideas please chime in.
> Add Restful API

- config/rbac/role.yaml
- controllers/flux/minicluster_controller.go
Just a minor fix to add RBAC rules. Let me know if I should make a changelog entry.
> Adding Service and Ingress RBAC rules to kubebuilder annotations

- TODO.md
- api/v1alpha1/minicluster_types.go
- controllers/flux/minicluster.go
- controllers/flux/templates/wait.sh
- docs/getting_started/custom-resource-definition.md
- examples/tests/lammps/minicluster-lammps.yaml
- script/check-output.sh
I am also testing increasing the default sleep for one-off commands, and falling back to using log.sh with a named container for a two container test case. I am running the current "two container" use case now (code is private hence I can't add here) and likely should add a dummy example for a test for one soon.
> diagnostics should be on level of container

- Makefile
- docs/development/developer-guide.md
- examples/dist/flux-operator.yaml
I want to see if it is possible to install the operator via just a yaml that points to a container, without needing to clone and do make deploy. It will depend on if the URLs provided here are relative to my cluster (e.g., 0.0.0.0 and 127.0.0.1) vs generic for any cluster (and relative to the pod node).
> testing generation of yaml

- .github/workflows/main.yml
- docs/getting_started/custom-resource-definition.md
This will close #70 - I think the check is fine in favor of having to deploy it somewhere else. I also think the flux-operator.yaml on the branch should consistently be provided that matches the state of the branch.
> add check that make build-config was run

- controllers/flux/templates/wait.sh
This shows there is quite a difference between flux start and flux mini submit, already in test cases.
```
Pods: flux-sample-0-fq6wb flux-sample-1-gqcht flux-sample-2-nvrvc flux-sample-3-zmfwn flux-sample-cert-generator
Pod: flux-sample-0-fq6wb
Actual:
hello world
FLUXTIME fluxsubmit wall time 0:00.30
FLUXTIME fluxstart wall time 0:16.59
```
This would be interesting to measure when all pods stay up.
> add time for flux submit and flux start

- sdk/python/v1alpha1/CHANGELOG.md
- sdk/python/v1alpha1/fluxoperator/client.py
- sdk/python/v1alpha1/fluxoperator/decorator.py
- sdk/python/v1alpha1/fluxoperator/defaults.py
- sdk/python/v1alpha1/fluxoperator/resource/pods.py
- sdk/python/v1alpha1/test/test_commands.py
- sdk/python/v1alpha1/test/test_container_resources.py
- sdk/python/v1alpha1/test/test_container_volume.py
- sdk/python/v1alpha1/test/test_flux_restful.py
- sdk/python/v1alpha1/test/test_flux_user.py
- sdk/python/v1alpha1/test/test_life_cycle.py
- sdk/python/v1alpha1/test/test_logging_spec.py
- sdk/python/v1alpha1/test/test_mini_cluster.py
- sdk/python/v1alpha1/test/test_mini_cluster_container.py
- sdk/python/v1alpha1/test/test_mini_cluster_list.py
- sdk/python/v1alpha1/test/test_mini_cluster_spec.py
- sdk/python/v1alpha1/test/test_mini_cluster_status.py
- sdk/python/v1alpha1/test/test_mini_cluster_user.py
- sdk/python/v1alpha1/test/test_mini_cluster_volume.py
- sdk/python/v1alpha1/test/test_pod_spec.py
If we want tight control of time (and a consistent way to time between users) the Flux Operator Python SDK should be able to hold basic times for bringing the minicluster up (to when all pods are completed or ready) along with deletion and waiting for the restful API service.
> fluxoperator python sdk client should time things

- examples/simulations/laghos-demos/minicluster.yaml
I looked at `make tests` and saw it was just running laghos, but with mpi run, so there are two ways of doing this:
- Give that command to flux submit to handle instead (in the PR here)
- Set the minicluster.yaml container to be a launcher, and still launch with mpirun and `make tests` (probably not what we want).
I found in practice the first was fast, and the second was much slower, maybe because it wasn't using all the resources available. Anyway, someone much smarter than me can fuddle with the parameters - this should get us started.
> adding laghos simulation

- api/v1alpha1/minicluster_types.go
- api/v1alpha1/swagger.json
- api/v1alpha1/zz_generated.openapi.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- controllers/flux/templates/wait.sh
- docs/getting_started/custom-resource-definition.md
- docs/tutorials/index.md
- docs/tutorials/singularity.md
- docs/tutorials/staging.md
- examples/dist/flux-operator.yaml
- examples/singularity/staging/minicluster.yaml
- hack/python-sdk/template/setup.py
- sdk/python/v1alpha1/CHANGELOG.md
- sdk/python/v1alpha1/docs/MiniClusterContainer.md
- sdk/python/v1alpha1/fluxoperator/models/mini_cluster_container.py
- sdk/python/v1alpha1/setup.py
A user might want to stage a container or other file assets to all workers before running a job.
> add tutorial for staging

- examples/simulations/sundials/minicluster.yaml
Likely to get the more complex examples working we will want to bind the mpi libraries to the host, OR build a container with sundials installed alongside flux to avoid singularity. Neither approach is the best, but for now this is a simple example that demonstrates it can work.
> add basic sundials example

- docs/tutorials/index.md
- examples/machine-learning/tensorflow/README.md
- examples/machine-learning/tensorflow/examples/cifar-10/download_data.sh
- examples/machine-learning/tensorflow/examples/cifar-10/main.py
- examples/machine-learning/tensorflow/minicluster.yaml
- examples/machine-learning/tensorflow/setup.py
- examples/machine-learning/tensorflow/tensorflow_flux/__init__.py
- examples/machine-learning/tensorflow/tensorflow_flux/tensorflow_flux.py
This example creates a tensorflow.distributed.Server using flux nodes, where the broker is the "main" runner (not sure if there is a terminology for that) and the rest are workers. They each set up communication via RPC and then the main node is able to coordinate training across the workers. Since we run with flux and the number of workers, this is running under the flux instance provided by the job.
I'm uneasy about having the example install via mamba at runtime, so likely I'm going to build a container with tensorflow (at time of writing looks like it's using 2.11.1, but I am falling back to v1 compat) so at least we have a container that can reproduce the demo running!
Also note the original example for ciphar-10 had 1000 epochs, but I figured that would take a really long time and …
> add tensorflow training example

- api/v1alpha1/minicluster_types.go
- api/v1alpha1/swagger.json
- api/v1alpha1/zz_generated.openapi.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- config/manager/kustomization.yaml
- controllers/flux/minicluster.go
- controllers/flux/templates/broker.toml
- controllers/flux/templates/wait.sh
- docs/getting_started/custom-resource-definition.md
- examples/dist/flux-operator.yaml
- hack/python-sdk/template/setup.py
- sdk/python/v1alpha1/.openapi-generator/FILES
- sdk/python/v1alpha1/CHANGELOG.md
- sdk/python/v1alpha1/docs/FluxSpec.md
- sdk/python/v1alpha1/fluxoperator/models/flux_spec.py
- sdk/python/v1alpha1/setup.py
flux is normally found on the path, but in the case of the hard coded paths for the imp and other associated files, we should allow the minicluster crd to customize the location.
This will close #166
> add support for custom flux install

- controllers/flux/job.go
- controllers/flux/minicluster.go
- controllers/flux/scale.go
- docs/tutorials/elasticity.md
- examples/elasticity/horizontal-autoscaler/minicluster.yaml
- sdk/python/v1alpha1/setup.py
we are currently using the headless service label, which is not ideal because we would include the pod for a sidecar service! This update will use a separate hpa-selector label instead, which will only select for the pods within the indexed job of the named minicluster
> unique label for hpa selector

- controllers/flux/extra.go
- controllers/flux/minicluster.go
- controllers/flux/minicluster_controller.go
- controllers/flux/pods.go
- controllers/flux/scale.go
- controllers/flux/service.go
- controllers/flux/volumes.go
the design I have seen  more often is to use the controller client directly on the reconciler. We cannot do that directly for Create since we have events (that require then name) but we can wrap the command and use r.New instead (and all others, r.Patch, r.Status, R.Get appear to work).
> cleanup client commands

- .github/workflows/main.yaml
- api/v1alpha1/minicluster_types.go
- api/v1alpha1/swagger.json
- api/v1alpha1/zz_generated.openapi.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- config/manager/kustomization.yaml
- controllers/flux/labels.go
- controllers/flux/minicluster.go
- controllers/flux/service.go
- docs/getting_started/custom-resource-definition.md
- examples/dist/flux-operator.yaml
- examples/tests/minimal-service/minicluster.yaml
- examples/tests/minimal-service/test.out.correct
- sdk/python/v1alpha1/docs/FluxSpec.md
- sdk/python/v1alpha1/fluxoperator/models/flux_spec.py
The minimal service setup only creates the headless service for the main broker pod, decreasing the networking overhead. In addition, I have needed to have a label to identify the broker several times, so it makes sense to add that.
> add support for index-based label and minimal service

- api/v1alpha1/minicluster_types.go
- api/v1alpha1/swagger.json
- api/v1alpha1/zz_generated.openapi.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- controllers/flux/minicluster.go
- examples/dist/flux-operator.yaml
- pkg/job/conditions.go
- pkg/job/job.go
- sdk/python/v1alpha1/docs/MiniClusterStatus.md
- sdk/python/v1alpha1/fluxoperator/client.py
- sdk/python/v1alpha1/fluxoperator/models/mini_cluster_status.py
we currently need a flag / status / label in argo to indicate that a minicluster is completed. We can derive this directly from the job, and pass forward the status to be used. I will test this with argo before merging
> support for minicluster finished status

- api/v1alpha1/minicluster_types.go
- api/v1alpha1/swagger.json
- api/v1alpha1/zz_generated.openapi.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- controllers/flux/minicluster.go
- examples/dist/flux-operator-arm.yaml
- examples/dist/flux-operator.yaml
- sdk/python/v1alpha1/docs/MiniClusterStatus.md
- sdk/python/v1alpha1/examples/interactive-submit.py
- sdk/python/v1alpha1/examples/state-pending-jobs-minicluster.py
- sdk/python/v1alpha1/fluxoperator/models/mini_cluster_status.py
status attributes are immuatable, and this is leading to bugs elsewhere, so while we are not actively using kubeflow I am removing this.
> remove completed label

- controllers/flux/minicluster.go
LabelSelectors multiple requirements are ANDed, however, the code was completely overriden the selector for the specific minicluster name, hence if there are multiple miniculster running in parallel the Service will expose all the indexed 0 pods from all the cluster.
> expose the index 0 pod for minimal service

- controllers/flux/job.go
- controllers/flux/minicluster.go
- controllers/flux/pods.go
Add soft rules for the Job so Pods prefer to be scheduled on the same zone and not to be scheduled on the same node.
This will improve the performance as pods in the same node will still resources from each other, and pods in different zone will have a performance penalty since networking is most likely to be worse.
> add pod affinity and antiffinity rules

- api/v1alpha2/minicluster_types.go
- api/v1alpha2/swagger.json
- api/v1alpha2/zz_generated.openapi.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- docs/getting_started/custom-resource-definition.md
- docs/tutorials/index.md
- examples/dist/flux-operator-arm.yaml
- examples/dist/flux-operator.yaml
- examples/distributed/dragonboat/Dockerfile
- examples/distributed/dragonboat/entrypoint.sh
- examples/distributed/dragonboat/minicluster.yaml
- examples/distributed/fractal/minicluster.yaml
- pkg/flux/templates/components.sh
- pkg/flux/templates/start.sh
- pkg/flux/templates/wait.sh
- sdk/python/v1alpha2/docs/Commands.md
- sdk/python/v1alpha2/fluxoperator/models/commands.py
Problem: we have to hack an init/pre command block for a custom script Solution: provide a commands->script that makes this easy. I am also adding two examples of distributed runs, one with raft dummy prototype (using dragonboat) and one with a custom distributed-fractal generator (image) tool that I made today! Here it is running!
> feat: api - add support to write custom script

- api/v1alpha2/minicluster_types.go
- api/v1alpha2/swagger.json
- api/v1alpha2/zz_generated.openapi.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- config/manager/kustomization.yaml
- controllers/flux/containers.go
- controllers/flux/volumes.go
- docs/getting_started/custom-resource-definition.md
- examples/dist/flux-operator-arm.yaml
- examples/dist/flux-operator.yaml
- examples/tests/emptydir/minicluster-without.yaml
- examples/tests/emptydir/minicluster.yaml
- sdk/python/v1alpha2/docs/ContainerVolume.md
- sdk/python/v1alpha2/fluxoperator/models/container_volume.py
Increasing the shared memory of the pod is important for IPC, which is important for MPI! Adding empty directory support here with type Medium should do that.
> feat: add support for empty directory

- Dockerfile
- api/v1alpha2/minicluster_types.go
- api/v1alpha2/swagger.json
- api/v1alpha2/zz_generated.openapi.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- controllers/flux/job.go
- controllers/flux/pods.go
- docs/getting_started/custom-resource-definition.md
- examples/dist/flux-operator-arm.yaml
- examples/dist/flux-operator.yaml
- pkg/flux/templates/components.sh
- pkg/flux/templates/wait.sh
- sdk/python/v1alpha2/docs/PodSpec.md
- sdk/python/v1alpha2/fluxoperator/models/pod_spec.py
runtimeClassName can be used to designate nvidia for skypilot.
It looks like we also need:
- an ability to designate specific labels for the leader (index 0) vs the workers. (doesn't seem hugely important)
- the running user must be sky (we have root) and thus the container needs sudo
> podspec: add additional features for podspec

- Dockerfile
- api/v1alpha2/minicluster_types.go
- api/v1alpha2/swagger.json
- api/v1alpha2/zz_generated.openapi.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- docs/getting_started/custom-resource-definition.md
- examples/dist/flux-operator-arm.yaml
- examples/dist/flux-operator.yaml
- go.mod
- go.sum
- pkg/flux/templates/components.sh
- sdk/python/v1alpha2/docs/FluxScheduler.md
- sdk/python/v1alpha2/fluxoperator/models/flux_scheduler.py
We do not spack load so fluxion does not show up
as the default. As a quick fix we can provide a script to unload sched-simple and load sched-fluxion-*
> fluxion: add support to easily load

- pkg/flux/templates/components.sh
for strict mode to work, the envars in the components scripts need defaults
> bug: fixes to envar defaults

- api/v1alpha2/minicluster_types.go
- chart/templates/minicluster-crd.yaml
- config/crd/bases/flux-framework.org_miniclusters.yaml
- examples/dist/flux-operator-arm.yaml
- examples/dist/flux-operator.yaml
A service name (defaulting to flux-service) that is shared by two MiniClusters can lead to a race condition, where one cluster is cleaning up (but the service still exists, associated with the deleting job) and then the new cluster coming up looks for it (and finds it) and does not recreate. In practice the network will fail to bootstrap. I believe we have seen this issue on the rabbit nodes, and I just saw it in scaling experiments. This change will test if the issue is resolved.
> bug: race condition for service name
